### PR TITLE
fix copy timeout

### LINKED ISSUE #6: Reset timeout when multiple items are copied in quick succession

### PR DESCRIPTION
**Pull request by fvrests**
resets timeout when copying a new variable

closes #6

### CODE REVIEW

File: src/lib/components/ingredients.svelte [hunk 1]
```diff
@@ -5,16 +5,16 @@
 	const variants = Object.keys(palette.variants)
 	const roles = Object.keys(palette.roles)
 
-	let copied = ['', '', '']
+	let copiedItem = ''
+	let timeout = setTimeout
```
Comment (mvllow) [inline src/lib/components/ingredients.svelte:9]: can we rename this to `copiedTimeout`?

File: src/lib/components/swatches.svelte [hunk 2]
```diff
@@ -5,14 +5,16 @@
 	const variants = Object.keys(palette.variants)
 	const roles = Object.keys(palette.roles)
 
-	let copied = ['', '']
+	let copiedItem = ''
+	let timeout = setTimeout
```
Comment (mvllow) [inline src/lib/components/swatches.svelte:9]: can we rename this to `copiedTimeout`?

**Review by mvllow — CHANGES_REQUESTED** [review]

**Review by mvllow — APPROVED** [review]
